// <auto-generated />
namespace PartyProductMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatedIdColumnNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedIdColumnNames));
        
        string IMigrationMetadata.Id
        {
            get { return "202311061039554_updatedIdColumnNames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
